### ISSUE TITLE
Criação de modelo conceitual do banco de dados

### ISSUE THREAD

**Issue by KleberTorres777** [KleberTorres777/Oriximin-Solid-ria#6]
Modelo conceitual do banco de dados relacionado ao projeto do aplicativo:

- [x] MER  
- [x] DER

**Comment by JosielSantos16** [comment]
Desejo ajudar nesta tarefa

**Comment by KleberTorres777** [comment]
Realizado como atividade da disciplina tópicos integradores do curso de Sistemas de Informação da Universidade Federal do Oeste do Pará (UFOPA):

[Modelos (MER E DER).pdf](https://github.com/user-attachments/files/18364925/ATIVIDADE_4.pdf)
